services:
  api-gateway:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api_gateway
    ports:
      - "8000:8001"
    environment:
      OPTIMIZE_EVENT_CONSUMPTION: "false"
      spring.cloud.consul.host: "dev-consul"
      spring.cloud.discovery.discovery.hostname: "api-gateway"
      spring.cloud.discovery.discovery.prefer-ip-address=false: "false"
      allowed-origins: http://localhost:3000
    networks:
      - finki_services_net

networks:
  finki_services_net:
    external: true