services:
  internship_db:
    image: postgres:17
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: internship
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5449:5432"
    container_name: internship_db
    networks:
      - finki_services_net
volumes:
  db-data:
networks:
  finki_services_net:
    external: true
